### ISSUE TITLE
support to open local files

### ISSUE THREAD

**Issue by legeng** [julescole/vue-audio-mixer#3]
This is a very good project, I hope to support opening files locally

**Comment by julescole** [comment]
@legeng This is already supported. Just include the relative or absolute URL of the track on the local server in the `url` field of the track config.

**Comment by legeng** [comment]
@julescole   thank you for your reply
I found some problems. For example, when I open the start button or recording button for the first time, it will report an error:
demo.js:1889 DOMException: Failed to execute'stop' on'AudioScheduledSourceNode': cannot call stop without calling start first.
     at VueComponent.stopSound (http://localhost:10001/demo.js:11145:25)
     at invokeWithErrorHandling (http://localhost:10001/demo.js:1855:28)
     at Vue.$emit (http://localhost:10001/demo.js:3883:11)
     at VueComponent.stop (http://localhost:10001/demo.js:12766:20)
     at VueComponent.saveAudioMix (http://localhost:10001/demo.js:12636:14)
     at invokeWithErrorHandling (http://localhost:10001/demo.js:1855:28)
     at HTMLButtonElement.invoker (http://localhost:10001/demo.js:2180:16)

However, there is no such problem with this one: http://www.realstrings.com/newmixer.html

I think this experience is better than direct download！

I hope you can think about it, thank you

**Comment by podi123** [comment]
Hi and good job !
i use wordpress and use your script..
i play in a band (for fun) and for work , its very good.

script modify with my mp3 links work but go everytimes to https://unpkg.com/....
anyway to go for the script to _"https://myhomesite/..."_

can i install on my own site by ftp ? just extract archive on root of website?
or it is obligatory to go to https://unpkg.com/  ?
Thanks in advance to explain
PS: a wordpress plugin will be very good!

**Comment by fawzyeltop** [comment]
yy

**Comment by fawzyeltop** [comment]
Is there js file instead of min js file for this project so I can edit it?
