### ISSUE TITLE
vue-audio-mixer is not compatible with vue 3 

### ISSUE THREAD

**Issue by premsgr** [julescole/vue-audio-mixer#9]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.__vue_render__$7 (vue-audio-mixer.esm.js:11436:93)
    at renderComponentRoot (runtime-core.esm-bundler.js:893:44)

**Comment by julescole** [comment]
A vue3 version will be released shortly. It is currently in BETA https://github.com/julescole/vue-audio-mixer/releases/tag/v2.0.0-beta
